version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: on-failure:3
    ports:
      - 5433:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    restart: on-failure:3
    environment:
      - spring.profiles.active=local
    ports:
      - 8080:8080
    depends_on:
      - database